### ISSUE TITLE
Restyle form and change app name in topbar

### ISSUE THREAD

**Issue by dakoalbeik** [Team-Clubroom/front-end#35]

**Comment by dakoalbeik** [comment]
The registration form needs to place the first name and last name fields side by side. Please update the application name in the top bar as well to CELDV

**Comment by cory-eheart-1** [comment]
I refactored the sign up form to feature the first and last name next to each other. To keep the hint text from going past the text field width, I reduced the padding of the input text on the left from 10 to 9. I also modified the name in the app bar.
